env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  no-console: off,
  import/extensions: off,
  no-underscore-dangle: off,
  consistent-return: off
}
